node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', '5fcef4d3-e6bb-4298-a603-cb3eec5fdb86') {
       def app = docker.build("devbuck/docker-jennodejs-demo:${commit_id}", '.').push()
     }
   }
}
